spring:
  datasource:
    url: jdbc:h2:mem:app;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
#    show-sql: true

### for debugging SQL parameters
#logging.level:
#  org.hibernate.orm.jdbc.bind: TRACE
