###
GET http://localhost:8080/

###
POST http://localhost:8080/members
Content-type: application/json

{
    "name": "이재서",
    "email": "asdf@asdf.com",
    "phoneNo": "010-1234-5678",
    "password": "asdf1234",
    "type": "STUDENT"
}


###
POST http://localhost:8080/lectures
Content-type: application/json

{
    "lecturerId": 2,
    "title": "자바 프로그래밍",
    "capacity": 30,
    "price": 10000
}